version: "3.8"
services:
    gateway:
        image: ${REGISTRY}/${LOGIN}/video-converter:gateway-${IMAGE_TAG}
        volumes:
            - /var/www/html:/var/www/html:ro
        ports:
            - "80:80"
            - "8080:8080"
            - "8081:8081"
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints: [node.role == manager]

    frontend:
        image: ${REGISTRY}/${LOGIN}/video-converter:frontend-${IMAGE_TAG}
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s

    api:
        image: ${REGISTRY}/${LOGIN}/video-converter:api-${IMAGE_TAG}
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            API_PORT: 8081
            POSTGRES_HOST: /run/secrets/postgres_host
            POSTGRES_PASSWORD: /run/secrets/postgres_password
            POSTGRES_PORT: 5432
            POSTGRES_USER: /run/secrets/postgres_user
            POSTGRES_DB: /run/secrets/postgres_db
            POSTGRES_SSL_MODE: disable
            PGDATA: /var/lib/postgresql/data
            GIN_MODE: release
        volumes:
            - ./secrets/development:/run/secrets:ro
            - files:/files
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 5s
        secrets:
            - postgres_password
            - postgres_user
            - postgres_db
            - postgres_host

    db:
        image: ${REGISTRY}/${LOGIN}/video-converter:db-${IMAGE_TAG}
        environment:
            POSTGRES_PASSWORD: /run/secrets/postgres_password
            POSTGRES_USER: /run/secrets/postgres_user
            POSTGRES_DB: /run/secrets/postgres_db
        volumes:
            - ./.database/postgres/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 5s
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
                window: 120s
            placement:
                constraints: [node.role == manager]
        secrets:
            - postgres_password
            - postgres_user
            - postgres_db

    zookeeper:
        image: wurstmeister/zookeeper:latest
        hostname: zookeeper
        ports:
            - "2181:2181" # только для отладки - на проде без портов, чтоб не достучаться

    kafka:
        image: wurstmeister/kafka:latest
        hostname: kafka
        ports:
            - "9094:9092"
            - "9092:9092"
#            - target: 9094
#              published: 9094
#              protocol: tcp
#              mode: host
        environment:
            #HOSTNAME_COMMAND: "hostname | echo kafka"
            KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
            #KAFKA_CREATE_TOPICS: notification:1:1 # notification:1:1,other_topic:1:1 -  должны создаться топики без всяких ограничений по времени  и размеру
            #KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
            KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
            #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
            #KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
            #KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_BROKER_ID: 1
            #KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
            #KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            #KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            #KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            #KAFKA_JMX_PORT: 9999
            #KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./zk-single-kafka-single/kafka1/data:/var/lib/kafka/data

volumes:
    files:

secrets:
    postgres_password:
        file: ./secrets/development/postgres_password
    postgres_user:
        file: ./secrets/development/postgres_user
    postgres_db:
        file: ./secrets/development/postgres_db
    postgres_host:
        file: ./secrets/development/postgres_host
