---
-   name: Add Certbot hook
    become: yes
    lineinfile:
        path: /etc/letsencrypt/cli.ini
        regexp: "^post-hook"
        line: "post-hook = docker service update --force video_gateway"
